### ISSUE TITLE
[BUG] FileNotFoundError when running examples

### ISSUE THREAD

**Issue by DeanLa** [charlesdong1991/py-roughviz#3]
When running example 2 I get:
```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/dean/anaconda3/envs/env/lib/python3.7/site-packages/roughviz/render/templates/jupyter_notebook.html'```

**Comment by DeanLa** [comment]
I copy pasted the file from github, it works now.
I guess the fix should be making `setup.py` put it in the correct location.

**Comment by charlesdong1991** [comment]
Oops, you are very right! Added `package_data` in `setup.py`, thanks very much! @DeanLa 👍 

Should be fixed if upgrading to the newest version
